### ISSUE TITLE
Allow max shop creation by player

### ISSUE THREAD

**Issue by lcdss** [EpicEricEE/ShopChest#10]
Use permissions (e.g. shopchest.limits.50) to define the max number of shops a player can create.

**Comment by EpicEricEE** [comment]
This can be set in the configuation and it will stay there (for now).

**Comment by lcdss** [comment]
How can I change the player limits (max number of shops) dynamically using a command?  It is this possible?

**Comment by EpicEricEE** [comment]
This is not possible yet, but I'll add a way to change all of the configuration values per command soon.
