### ISSUE TITLE
Players can sell in creative mode

### ISSUE THREAD

**Issue by Jackieeex143** [EpicEricEE/ShopChest#100]
I have sharecontrol on my server and users can buy and sell in creative, even though I disabled interacting with chests AND armor stands in the sharecontrol config. So right now no one on my server can sell items in shops, and I really wanna enable this or I gotta remove the entire plugin since selling is crucial on my server.

**Comment by Jackieeex143** [comment]
Oh, okay... Closed the thread without helping... 10/10 great customer service.

**Comment by EpicEricEE** [comment]
I closed it with a commit, that means the fix will be implemented with the next update. If you want, you can download the latest build, that already has it fixed, [here](http://epiceric.square7.de/bukkit/ShopChest/).
