### ISSUE TITLE
Add admin/console command

### ISSUE THREAD

**Issue by weberlepecheur** [EpicEricEE/ShopChest#101]
It is possible to add a command that allows to delete all the shops of a particular player, to remove the chest and / or the contents of it.

Like /shop removeall Notch - Removes all player's shop
Or similar

Because I will need this to automate a commercial place, when the player becomes absent or inactive, his shops are withdrawn.

**Comment by EpicEricEE** [comment]
I'm going to add that, but the command will only remove the shops, but not the chest or its contents.
