### ISSUE TITLE
ChestShop 1.12?

### ISSUE THREAD

**Issue by FrankHeijden** [EpicEricEE/ShopChest#102]
Is chestshop going to be compatible with 1.12? For now it has an instantcrash of the server xD

**Comment by EpicEricEE** [comment]
Which version are you using?
The latest version (1.11.1) is not causing the server to crash for me, but it does not support item names from 1.12. If you are using a developer build from [here](http://epiceric.square7.de/bukkit/ShopChest/), this plugin should work stable on 1.12. The next official update of ShopChest will be released very soon after the official release of Minecraft 1.12.

**Comment by FrankHeijden** [comment]
Oh weird. using the # 11 build.

**Comment by FrankHeijden** [comment]
Oh wait..... using the wrong issue tracker o_O

my plugin is chestshop and not shopchest xD

**Comment by EpicEricEE** [comment]
Was about to say that ✌️
