### ISSUE TITLE
Economy not working

### ISSUE THREAD

**Issue by SrPeterr** [EpicEricEE/ShopChest#103]
Hi, 
I am trying to create a shop, but everytime I do, it says that i havent got enough money, but i have!
https://i.gyazo.com/3a1ef1f55294efa40015a813f3cd5c4b.png

I am currently using CraftConomy: https://www.spigotmc.org/resources/craftconomy.2395/

What could be the problem?

**Comment by SrPeterr** [comment]
It looks like Essentials eco y overwritting CraftConomy....

**Comment by EpicEricEE** [comment]
Could it be because of CraftConomy being a multi-world economy plugin?

**Comment by SrPeterr** [comment]
Yep, It was craftconomy multi-world, tried another plugin :P
Thanks for your time!

**Comment by EpicEricEE** [comment]
Should be fixed in 48eda92
