### ISSUE TITLE
you don't have permission to by something here

### ISSUE THREAD

**Issue by rock211212** [EpicEricEE/ShopChest#108]
![2017-06-18_13 03 38](https://user-images.githubusercontent.com/25649691/27258206-33c08b94-5427-11e7-8e14-b03f9c6c6722.png)
I have tried it give shopchest.external.bypas and shopchest.extend.protected 。
set gorldguard flag to allow-shop 。
I found only two ways to work. remove worldguard or give Permissions shopchest.*
I think it might be a problem of Permissions

**Comment by EpicEricEE** [comment]
You need to also allow the WorldGuard flag _chest-access_ to allow shop creation. The permission _shopchest.external.bypass_ (with two 's') should also work.

**Comment by rock211212** [comment]
I tried it
This does not work

**Comment by EpicEricEE** [comment]
Please enter _/rg info_ in the region with the shops and show me the chat output.

**Comment by rock211212** [comment]
![2017-06-20_22 54 13](https://user-images.githubusercontent.com/25649691/27339893-98de3fc2-560b-11e7-979f-5f6a21802213.png)
The original is the problem of worldguare
Think's for your help

**Comment by rock211212** [comment]
The problem is not resolved
Finally I dropped two plugins to 1.10
