### ISSUE TITLE
Deleting chest inventories

### ISSUE THREAD

**Issue by Demonkid1112** [EpicEricEE/ShopChest#109]
So I have suspension that your plugin has been deleting players chest inventories. The last two nights the console has popped up with the following issue 
https://pastebin.com/q88ya4rh

Then a minute later everyone starts complaining about their stuff being gone. No other errors pop up, nor do I block any errors from my console from being shown. This is heavily irritating. I can't be 100% sure it is your plugin but all signs point to it.

extra info:
Spigot 1.12 ,Using version 1.12.2 chest shop, I use MySQL, https://pastebin.com/ah9YvULz - config.yml sql data is commented out its correct in file. And lastly it appears to only affect chest in loaded chunks.

**Comment by Demonkid1112** [comment]
#note#
The chest being wiped include normal chest and shop chest.

**Comment by EpicEricEE** [comment]
Did you try to remove the plugin and see if the issue persists?
