### ISSUE TITLE
Trading Items

### ISSUE THREAD

**Issue by roastchicken** [EpicEricEE/ShopChest#112]
I saw this plugin on SpigotMC when searching for a shop plugin. Your plugin seems to be very full-featured and I would love to use it, however I'm not sure if it can fit my use case. I play on an almost-vanilla server that just has a few utility plugins. We currently have shops set up with the honor system, which I think is a bit precarious. I think a shop plugin would be very useful, but I don't think the server owners would want to add an economy plugin to use shops.

Is it possible to configure this plugin to allow simple trades? For example, buying a stack of wood with one diamond instead of for some amount of money in an economy plugin. If not, is this something you could envision adding to the plugin in the future?

**Comment by EpicEricEE** [comment]
Sorry, but I have no plans to add this in the near future.
