### ISSUE TITLE
Different permissions for different number's of shops?

### ISSUE THREAD

**Issue by Junior1544** [EpicEricEE/ShopChest#113]
in the spigot webiste on the page about this plugin, it says how to set the default number of shops a person can make but it mentions that they can make more if they have permissions to do so.

How can i set these permissions?  I use the PEX plugin for permissions but i don't see any nodes for shopchest number of shops...

Thanks for the help!  This is a wonderful plugin and my users love it!

**Comment by EpicEricEE** [comment]
It's _shopchest.limit._``X`` where ``X`` stands for the limit you want to give the player.

**Comment by Junior1544** [comment]
Thanks!
