### ISSUE TITLE
you don't have permission to by something here

### ISSUE THREAD

**Issue by Pringell** [EpicEricEE/ShopChest#115]
set up permissionEX added everything correctly and says you don't have permission to by something here set up flags (allow-shop chest-access) but only works with shopchest.* and on the other nothing works
![default](https://user-images.githubusercontent.com/29713140/27552544-7c0106d8-5ab0-11e7-991d-d9bb1e47d9a3.png)

**Comment by EpicEricEE** [comment]
It's not _allow-shop_, it's _create-shop_, _use-shop_, and _use-admin-shop_.

**Comment by Pringell** [comment]
Thank
