### ISSUE TITLE
Shop with ID Create not found

### ISSUE THREAD

**Issue by sirbucsalot** [EpicEricEE/ShopChest#116]
Hi,

In trying to create shops our users get the following error: shop > Shop with ID create not found. The command they are using is:

/shop create 1 20 20  - trying to create a shop. 

Any ideas why this may be happening? I am on 1.12

**Comment by EpicEricEE** [comment]
Are you sure you're using ShopChest? Or do you have another plugin using the command "shop"?

**Comment by sirbucsalot** [comment]
Yep, using shopchest and following the instructions provided:

Make sure you have permission
Make sure you have enough money
Make sure you hold the item you want to sell in your hand
/shop create <amount> <buy-price> <sell-price>
You can set buy-price or sell-price to 0 to disable buying or selling
Click the chest which should be the shop
If not already done, put the items inside the chest

**Comment by EpicEricEE** [comment]
But the message you're getting cannot be thrown by ShopChest
