### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by ColtonDRG** [EpicEricEE/ShopChest#12]
I noticed you have no LICENSE file in your repository. I am running a server with some friends and we want to use this plugin, but I would like to make some minor changes first. Am I allowed to alter the code and make my own version? What license is this under, if any?

**Comment by EpicEricEE** [comment]
Yes, I should probably add a license file as soon as possible, but for now I'd say, as long as you don't publish it, you can change as much as you want. If you have an idea, which license I should use for this, please tell me as I don't know very much about them.

**Comment by EpicEricEE** [comment]
Added a LICENSE file, so you can do what you're allowed to :smile:
