### ISSUE TITLE
Does not function correctly with 1.12

### ISSUE THREAD

**Issue by Skizzy77** [EpicEricEE/ShopChest#121]
Hi there.

I was using this shop on my 1.11.2 server, and then we went ahead and updated the server to 1.12. Along with it, we downloaded the latest version of your plugin.

Our shops still showed up. Like you could see the floating blocks and floating text and stuff, but no one could buy or sell anything. It displays no errors, and I am honestly just stumped.

Works great with 1.11.2 though.

**Comment by EpicEricEE** [comment]
Now, if you told me what error you're getting, I could help you.

**Comment by TheZenKitteh** [comment]
Try putting the server into debug, but don't leave it there long. Then have someone try to buy/sell to a shop then disable debug and look over the logs. That's how I find most of the errors I get from time to time. With the error, you can then tell the plugin dev and they can fix it or suggest how you can fix it if it's specific to your setup.

**Comment by dan-nkl** [comment]
Works absolutely fine one my Spigot 1.12 Server. Not using Worldguard.
