### ISSUE TITLE
bulk trade

### ISSUE THREAD

**Issue by wolfwork** [EpicEricEE/ShopChest#122]
I suggest the function that can sell/buy items by bulk.
Or the fuction to mass sell.
I think it would be nice if it is triggered using shift.

**Comment by EpicEricEE** [comment]
You can already shift-click to buy or sell a stack.

**Comment by wolfwork** [comment]
I think it shoud be nice when sell/buy all items in inventory.
When mass transactions are required, like ore and crops
Users are annoyed to click 36 times

**Comment by EpicEricEE** [comment]
Maybe I'll eventually add a config option.
