### ISSUE TITLE
Cannot find vault on 1.12 paperspigot server

### ISSUE THREAD

**Issue by CBM1014** [EpicEricEE/ShopChest#125]

**Comment by EpicEricEE** [comment]
What's the issue?

**Comment by CBM1014** [comment]
oh sorry

**Comment by CBM1014** [comment]
cannot fand vault on 1.12 paperspigot server

**Comment by CBM1014** [comment]
http://oqpu2omvh.bkt.clouddn.com/17-7-16/55537320.jpg

**Comment by EpicEricEE** [comment]
Vault is just the bridge between this plugin and an economy plugin, but you don't have an economy plugin installed. So, just install an economy plugin like Essentials Economy or an other one and it should work.

**Comment by CBM1014** [comment]
Thanks a lot.
