### ISSUE TITLE
Doesn't load shops from mysql after server start

### ISSUE THREAD

**Issue by Lbleu** [EpicEricEE/ShopChest#13]
I'm using spigot 1.10 and the latest version of the plugin, when I start the server it connects sucessfully and loads the shops correctly, but if I try to reload the plugin or enable the auto reload option it doesn't load the shops anymore (doesn't throw any errors on console) just 
[ShopChest] Using locale "en_US"
[ShopChest] Successfully reloaded 0 shops.

**Comment by EpicEricEE** [comment]
I've no idea what is causing this, but could you send me your _shops.db_ file (if you're using SQLite) and the configuration file?

**Comment by Lbleu** [comment]
I'm using MySQL, here's the config http://pastebin.com/jNFqp2FR

**Comment by EpicEricEE** [comment]
Okay... 
Maybe your MySQL server or the way this plugin supports MySQL is causing this. Unfortunately I only have a local MySQL server on my computer (and it works well there) so I can't test how long it would take for 300+ shops to get loaded, as that might also be causing it.

**Comment by EpicEricEE** [comment]
Okay... 
Maybe your MySQL server or the way this plugin supports MySQL is causing this. Unfortunately I only have a local MySQL server on my computer (and it works well there) so I can't test how long it would take for 300+ shops to get loaded, as that might also be causing it.
You can download a version of ShopChest [here](https://drive.google.com/open?id=0BxqKmdgOnShjMDIyQ3NSY0hwbW8), which displays in the console, when the shops get loaded, and how many entries were found in the database when initializing it.

You should get something like this:
![consoleoutput](https://cloud.githubusercontent.com/assets/7191192/17291995/6def23ee-57e7-11e6-82e1-a16d8e6729c6.PNG)

**Comment by EpicEricEE** [comment]
Now, I got another ShopChest version which displays a lot about about the loading progress of the shops.
You can download it [here](https://drive.google.com/open?id=0BxqKmdgOnShjTnE2aGJfNkdyN2c). To prevent console spam, I decided to write the messages in an extra file  _(plugins/ShopChest/debug.txt)_. Please send me the contents of this file. Thank you :+1:

**Comment by Lbleu** [comment]
Sorry for the delay, here's the log: http://pastebin.com/97eX1SfB

**Comment by EpicEricEE** [comment]
Thank you. I'll give you another version, with the latest commits, so it should completely reconnect to the database after a reload or a shop reload, and close the old connection what it hadn't done before.
You can download it here, and if it still doesn't work, please set _enable_debug_log_ in the configuration to _true_ and send me the _debug.txt_ file after you stopped the server _(no reload please, as the file will be overwritten after a plugin reload. You need to stop the server, so the disable-section is still available to read)_.

You can download it [here](https://drive.google.com/open?id=0BxqKmdgOnShjLWRJZ2gxSjZZOUk).

**Comment by Lbleu** [comment]
Hello, It seems to be fixed now :+1:  now it reloads the shops with a single /shop reload instead of requiring two, but i've tried loading the server with debug enabled (without any reload, just starting the server and checking the debug log) and it keeps throwing some NullPointerException. Here's the log: http://pastebin.com/YQMDwSGF
Anyways, it's working so good job :)

**Comment by EpicEricEE** [comment]
Perfect! The NullPointerExceptions are thrown when an ID was not found in the database, but that's fine.

For example:
I have 10 shops in the database (ID 1-10) and remove the shop with ID#4. Now ID#4 is no longer in the database, so if I reload the shops, it thrown an NullPointerException because ID#4 was not found.
