### ISSUE TITLE
Feature Suggestion: Random shop

### ISSUE THREAD

**Issue by TheZenKitteh** [EpicEricEE/ShopChest#133]
So I was thinking, it would be neat to be able to create a shop that you put in whatever items and when a user buys an item from the shop, they get a random item from the chest.

This would be great for a record shop. Throw in a variety of records and the buyer gets a random one from the chest when they buy.

Another example would be sort of a gambling shop. A shop that mostly sells something cheap like dirt, sand, or cobble but with a few diamonds, emeralds, etc mixed in so the buyer has a chance at getting a costlier item for the same price as the lower priced item.

**Comment by EpicEricEE** [comment]
I will not add this, because I think that fits better in a plugin for fun or games. Maybe it is possible for another developer to create an extra plugin for that with the ShopChest API.
