### ISSUE TITLE
Players Can Create Shops on Protected Chests

### ISSUE THREAD

**Issue by ToxicCharm** [EpicEricEE/ShopChest#14]
Hello!

Thank you for the great plugin! I have one issue. 

When a player has a chest within his/her land claim (GriefPrevention), other players can create a shop on it, open it, and remove the contents.

I made sure the shopchest.create.protected was removed = still didn't work
I made the permission negative = still didn't work

How can I fix this?

Thank you for your time.

**Comment by EpicEricEE** [comment]
It's difficult to support every protection and plot plugin as there are a lot available. The only supported plugins are LWC and Lockette. 

However, I have an idea: If I check if a player could open the chest where he wants to create a shop, he is allowed to create one. If any other plugin would prevent him to open it, he is not allowed. 
For example if I bought a plot with any plot plugin, the plugin should prevent every other player from opening my chests and as they can't open it, Shopchest won't allow them to create a shop there

**Comment by ToxicCharm** [comment]
Hi,

That solution worked. :)
One more question, I am getting this warning in my console after updating today:

WARN Using default value for: message.noPermission.create-protected (&amp;cYou don't have permission to create a shop on a protected chest.)

Is this okay? 

Thank you again!

**Comment by EpicEricEE** [comment]
This is just to inform you that the value is not entered in the language file and as I added a new message, it won't be added in the file automatically. If you haven't changed anything in the _.lang_ files, you can delete them so ShopChest generates new ones. If you have modified them, you can add the line

_message.noPermission.create-protected=&cYou don't have permission to create a ShopChest on a protected chest_

into the language files and translate or change them however you want
