### ISSUE TITLE
Paying for shops

### ISSUE THREAD

**Issue by TheCactusMonkey** [EpicEricEE/ShopChest#140]
Hi, i have used this plugin for 3 days now and i like it alot.
But is there a way to make it possible to make that you have to pay like 10k $ to make 1 chest shop?

Thanks,
TheCactusMonkey

**Comment by EpicEricEE** [comment]
It should be in the config at _creation-price_.

**Comment by TheCactusMonkey** [comment]
Thanks, i found that and it works!
But what is the diffrents between Player(normal) and Admin shops?

**Comment by EpicEricEE** [comment]
Admin shops have an infinite stock.
