### ISSUE TITLE
Console error message every hours

### ISSUE THREAD

**Issue by Noiknez** [EpicEricEE/ShopChest#148]
Hi, I got theses messages every hours on the server, I just put it here

https://pastebin.com/GT3W3JJ9

**Comment by FranciscoContreras** [comment]
I'm running into the exact same problem and I'm not sure how to resolve it, unfortunately.

**Comment by EpicEricEE** [comment]
Your MySQL connection seems to have died and the plugin didn't create a new one. Should be fixed with 78384eb.
