### ISSUE TITLE
Purge database

### ISSUE THREAD

**Issue by MineTheCube** [EpicEricEE/ShopChest#154]
Hi,

I use the SQLite database, but it seems to be indefinitely growing (currently bigger than 100mb). It would be great if you could clear old data at server start or stop.

Thanks!

**Comment by sigmaroot** [comment]
As a tip: If it becomes such a huge size, you can clean up it yourself by opening it with SQLite DB Browser (http://sqlitebrowser.org/) and the following sql commands:

`DELETE FROM shop_log;`
`VACUUM;`
`UPDATE sqlite_sequence SET seq = 0 WHERE name = 'shop_log';`

This should clean out the shop log (that's the only table that may cause such a huge size and the only one you can clean up).

**Remember to make a backup copy of that database before editing it manually!**

And by the way: As far as I have seen in the code, ShopChest do vacuum the database on every server stop. So there's nothing more to do. I guess it is the shop log that becomes such a huge size. If you don't want to edit the database on your own at first, you can try to disable the log by setting **enable-economy-log** to **false** in your **config.yml**. This way you can see if it stops growing.

**Comment by MineTheCube** [comment]
What I'm asking here is more like auto-deletion of old logs (+30 days for instance), so we don't have to do this manually.

**Comment by sigmaroot** [comment]
I've implemented a way to enable / disable auto log cleanup and to set a time diff in days:

https://github.com/sigmaroot/ShopChest/commit/c70f8d9e2491006d8361a389a98b9c79528de29d

PR will follow!
