### ISSUE TITLE
ShopChest Issue

### ISSUE THREAD

**Issue by Yeihlouh** [EpicEricEE/ShopChest#158]
I have all the permissions set up for ShopChest on my server. Admin shops work fine, but nobody has permission to use player shops. I've tried everything. After searching my issue, nobody has had the same problem. Help! (And no, it's not a WorldGuard issue)

**Comment by EpicEricEE** [comment]
Please enable the debug log in the config (if not already done), restart or reload the server, try buying something again and then show me the debug.txt file.

**Comment by Yeihlouh** [comment]
Here you go:
[02/11/2017 16:44:04] Cookie_Clicker wants to buy
[02/11/2017 16:44:04] Cookie_Clicker doesn't have external plugin's permission
Are there any plugins that are known to cause issues with ShopChest?

**Comment by EpicEricEE** [comment]
If you have PlotSquared installed, maybe you haven't set up it's flags. It has to be a problem with flags WorldGuard or PlotSquared, as they are the only cause for the denial. If you want to, you can show me a screenshot of the flags (WorldGuard and PlotSquared if you have it) to have me check it.

**Comment by Yeihlouh** [comment]
The player shops are not in a WorldGuard region. Players are not allowed to create shops in those regions. Is there a universal region where I can enable shops? That may be it.

**Comment by EpicEricEE** [comment]
Yes, there is the region *__global__*. You can also set the default value of the flags in the config.

**Comment by Yeihlouh** [comment]
Oh, that's gotta be it. I will try to add permissions in thatregion. I will tell you if it works or not!

**Comment by Yeihlouh** [comment]
It worked! Thanks for the help!
