### ISSUE TITLE
You don't have the permission to buy something here

### ISSUE THREAD

**Issue by johnsoncui02** [EpicEricEE/ShopChest#166]
You don't have the permission to buy something here

![image](https://user-images.githubusercontent.com/23487437/33937907-2167d3de-dfba-11e7-8914-92507ff5b5aa.png)

![image](https://user-images.githubusercontent.com/23487437/33937928-39149f62-dfba-11e7-8b20-48372abe1288.png)

![image](https://user-images.githubusercontent.com/23487437/33937936-3f0d29ca-dfba-11e7-9395-b8174ee4fd5c.png)

**Comment by EpicEricEE** [comment]
Set the flags for the global region.

**Comment by johnsoncui02** [comment]
so sorry, i read the whole thing again and realize there's a FAQ section all the way on the bottom. My apologizes.
