### ISSUE TITLE
ShopChest PlayerTeleportEvent Console Error

### ISSUE THREAD

**Issue by Noiknez** [EpicEricEE/ShopChest#17]
Hi, with the new version of ShopChest i got this error in the console when starting the server :
http://pastebin.com/di8Xf6L3
I see shopchest and citizen2, should i see in the citizen2 side for this error ? It happen only with the new version of shopchest 1.10.1
Also lag start to appear only when selling items (maybe is just the mysql part that i have misconfigurated)
Spigot version :  CraftBukkit version git-Spigot-1e4dd71-5e5cf84 (MC: 1.10.2)

Thank you in advance for your help

**Comment by EpicEricEE** [comment]
No this is my mistake, because I didn't check if the worlds are the same before measuring the distance of the player and the shop, and of course, you can't measure a distance when the locations are not in the same world.

**Comment by Noiknez** [comment]
Ok, i will just wait the next version of the plugins ! :+1:

**Comment by Noiknez** [comment]
Hi, with version 1.10.2 i got another PlayerTeleportEvent, i link it here
http://pastebin.com/4dc4gRwv
The work that you provide on this plugin is amasing
Regards

**Comment by EpicEricEE** [comment]
This is fixed in the next version (c8f4e89)
