### ISSUE TITLE
[BUG] AuthMe Integration

### ISSUE THREAD

**Issue by Jariway** [EpicEricEE/ShopChest#175]
So if you are using AuthMe on your server you won't have any problem. The problem comes when you have AuthMe installed but you disable the plugin using the commands given by the plugin. This is the error I get: https://i.imgur.com/y3wU6en.png

You can fix it by enabling AuthMe again or just removing the plugin.

**Comment by EpicEricEE** [comment]
Disabling a plugin while the server is running literally calls for issues for plugins that hook into it. Won't fix.
