### ISSUE TITLE
[ShopChest] No Chest found in world

### ISSUE THREAD

**Issue by Phyther** [EpicEricEE/ShopChest#183]
Using the latest version.
Receiving the following warnings and would like to remove from the database:

27.03 19:55:53 [Server] ERROR [ShopChest] No Chest found in world 'Towny' at location: -3116; 69; -4447
27.03 19:55:53 [Server] ERROR [ShopChest] No Chest found in world 'Towny' at location: -3119; 69; -4447
27.03 19:55:53 [Server] ERROR [ShopChest] No Chest found in world 'Towny' at location: -3115; 69; -4434
27.03 19:55:53 [Server] ERROR [ShopChest] No Chest found in world 'Towny' at location: -3124; 69; -4447
27.03 19:55:53 [Server] ERROR [ShopChest] No Chest found in world 'Towny' at location: -3121; 69; -4447
27.03 19:55:53 [Server] ERROR [ShopChest] No Chest found in world 'Towny' at location: -3127; 69; -4447

**Comment by EpicEricEE** [comment]
Enable ``remove-shop-on-error`` in the config.
