### ISSUE TITLE
restart server then all shop disappear

### ISSUE THREAD

**Issue by khlfkk** [EpicEricEE/ShopChest#191]
It is very buggy.. so disappointed. Now it is 5 times for my server....

Paper version git-Paper-1430 
ShopChest version 1.12.3

MYSQL version.

**Comment by madolebr** [comment]
same exact thing just happened to my server when we updated to paper. and i really love this plugin. hope to see the issue solved. would help if you posted the error log tho

**Comment by EpicEricEE** [comment]
This only happens with Paper, but it should be fixed with 7874262 (wait for the next update).
