### ISSUE TITLE
Very high memory usage

### ISSUE THREAD

**Issue by Scarsz** [EpicEricEE/ShopChest#192]
The [`ShopUtils.playerLocation`](https://github.com/EpicEricEE/ShopChest/blob/master/src/main/java/de/epiceric/shopchest/utils/ShopUtils.java#L22) map is taking up over 3GB of memory on a live server. Is this map not being properly cleaned? Could this be an incompatibility with Citizens?

![Memory usage](https://scarsz.me/i/rukuw.png)
![Citizens](https://scarsz.me/i/vmdep.png)

**Comment by madolebr** [comment]
wow thats insane usage. we didnt see anything like that on ours. we have citizens 2 on our server and had no issues with it.

**Comment by Scarsz** [comment]
If I had to guess, the plugin is logging position data for Citizens NPCs in the map, even beyond when Citizens doesn't want the objects anymore. Garbage collector can't dispose the old NPC data because it's stuck in the map. Implementing a check to make sure only players have their data inputted might be a fix for this.

I've never dabbled with Citizens though, so I don't know for sure.

**Comment by EpicEricEE** [comment]
Should have been fixed with 3b9d26c (only storing UUID instead of whole player object)
