### ISSUE TITLE
Dev builds + maven repository

### ISSUE THREAD

**Issue by sgdc3** [EpicEricEE/ShopChest#199]
I added ShopChest to my jenkins and nexus instances:

CI: https://ci.codemc.org/job/EpicEricEE/job/ShopChest/
Maven repo: https://repo.codemc.org/repository/maven-public/

You can login into jenkins using your github credentials (it uses the github oauth) and edit the build job as you want.

**Comment by EpicEricEE** [comment]
Oh that's nice, thank you 👍
