### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by GothkittyGirl** [EpicEricEE/ShopChest#203]
allow multiple items per shop? and random item for a price type thing?

**Comment by EpicEricEE** [comment]
That would be too big of a feature to implement.
I think the basic concept of player shops with a clearly defined product and price should stay the way it is, so only some (more or less) minor changes (e.g. item preview), will happen in the future.

**Comment by GothkittyGirl** [comment]
ok thats cool just thought id ask loving the plugin so far :)
