### ISSUE TITLE
new issue

### ISSUE THREAD

**Issue by GothkittyGirl** [EpicEricEE/ShopChest#204]
No error in console just the holograms not working now

**Comment by GothkittyGirl** [comment]
2 restarts fixed this. not sure what was going on but looks to be fine now

**Comment by EpicEricEE** [comment]
I also had that once, but could not reproduce it 🤷‍♂️

**Comment by GothkittyGirl** [comment]
i had updated this morning/afternoon with newest update and the restart did something i think but not checked the logs so sure but next restart fixed it
