### ISSUE TITLE
Beef Hologram crashes client.

### ISSUE THREAD

**Issue by Votyn** [EpicEricEE/ShopChest#210]
Version: ShopChest-1.13-SNAPSHOT
Minecraft Version: 1.13.1
Other relevant plugins: Spigot, Vault, EssentialsX, EssentialsX Chat.
When creating any shop with beef, the cooked variety, the client crashes upon looking directly at the beef with an error something along the lines of "Crashed while loading entity in your world". It is to be noted that the beef can be seen very well in your peripheral vision, but as soon as you attempt to load the text around it, it appears, the game will crash (client, not server.)

This is the only issue I have found so far with ShopChest in 1.13.1, loving it! :grin:

**Comment by EpicEricEE** [comment]
Can't reproduce

**Comment by DracarysPro** [comment]
You should add support for Paper, in 2018 half the servers use paperspigot.

**Comment by Votyn** [comment]
No, I was not using paper, but I have just updated to the most recent snapshot of ShopChest and the issue appears to be fixed. Thank you! :)
Love this plugin.
