### ISSUE TITLE
Ruined my server spawn.

### ISSUE THREAD

**Issue by adamlaughlin** [EpicEricEE/ShopChest#211]
I am running the latest shopchest.
Have created four admin chests at spawn. Was using MySQL.
Created some wrong, removed them with shop remove.
Created them properly again.
Restarted server, old holograms were still there along with the new ones. Unreadable.
Switched to Flatfile SQLite as the MYSQL was firing errors at startup anyways (it is broken.)
Now all of the old holograms are still there, but the shops are gone.
Re-created the shops.
Still have layer after layer of holograms.
Deleted plugin and flatfile to remove them.
Switched from Paper to Spigot.
Didn't work.  Holograms still there.
Lagging insanely as soon as entering spawn.

Update:
Coreprotect did nothing.  Solved with CMI - /cmi killall -named (range)

**Comment by silverforte** [comment]
This is happening on my server. I didn't even remove the chests before the issues started. I went to old admin shops and saw the holograms were different than I remember. They were with black backdrop and lagging pretty badly. Anyone near the holograms had constantly low framerates and deleting the shops rarely worked, usually feeding back an error about how I can't break them. If I was able to, the holograms remained. Now there are just floating holograms causing lag.

**Comment by LGrinnan** [comment]
I'm having this same issue. Did you all find a fix? It seems the creator of this plugin hasn't been responsive :/

**Comment by silverforte** [comment]
No, I did not find a solution. Someone said killing all entities helps and I didn't find that to be the case. I gave up on this plugin and, quite frankly, because so many plugin authors overcharge for their plugins and also go inactive after accruing a certain number of purchases, I have given up on hosting a server and am waiting on Hytale.

**Comment by EpicEricEE** [comment]
Should be fixed with the latest snapshots (although other things probably cause issues)
