### ISSUE TITLE
ShopChest locks the server: "The server has not responded for x seconds! Creating thread dump"

### ISSUE THREAD

**Issue by kamild1996** [EpicEricEE/ShopChest#212]
The issue happens after updating Paper to the latest build (#227). Yes, I know you do not support Paper for some reason, but I've been told by a Paper dev that this bug actually isn't specific to Paper.

[2018-09-08-4.log](https://github.com/EpicEricEE/ShopChest/files/2363120/2018-09-08-4.log)

**Comment by EpicEricEE** [comment]
Please try again with the latest build, it should be fixed. If not, let me know.
