### ISSUE TITLE
Wrong update alert message

### ISSUE THREAD

**Issue by JohOply** [EpicEricEE/ShopChest#224]
Hi
I use latest dev build (b36). On startup and at each connection, it displays `[17:47:14 WARN]: [ShopChest] Version 1.12.3 is available! You are running version 1.13-SNAPSHOT.`

**Comment by EpicEricEE** [comment]
The updater only checks if the versions match, and when using a snapshot, they don't, so the message is shown. If you want to get rid of the join notification, you'll have to disable the update checker in the config (the check at startup will stay).

**Comment by JohOply** [comment]
Okay, I understand! It was only to inform you in case it was not wanted :)
