### ISSUE TITLE
Could not find translation for "" in selected language file. Using default translation ()

### ISSUE THREAD

**Issue by comonier** [EpicEricEE/ShopChest#226]
https://codeshare.io/5gP0v0

example:  [ShopChest] Could not find translation for "block.minecraft.acacia_sapling" in selected language file. Using default translation (Acacia Sapling)

how to easy solve this issue ?

**Comment by EpicEricEE** [comment]
With 1.13, the language files have changed, so you need to let the plugin recreate them (delete or backup, then restart/reload server). If you have customized the messages, you can paste them into the newly created file.
