### ISSUE TITLE
Sell all items in hand. 

### ISSUE THREAD

**Issue by JoshuaJoppie** [EpicEricEE/ShopChest#227]
Can you please fix it so either, if you have 59items in hand, it still will sell them all holding shift, and not say "You don't have 64, aka a stack!"... that or make a sell all shortcut (you can detect when the player PickBlocks aka middle mouse button, or even if they are sprinting with CTRL, both are viable fixes.)

**Comment by EpicEricEE** [comment]
You could enable `auto-calculate-item-amount` in the config to be able to sell a stack, or – if you don't have a full stack – as much as you have, by holding shift.
