### ISSUE TITLE
Compilation issue with Java 8

### ISSUE THREAD

**Issue by MineTheCube** [EpicEricEE/ShopChest#23]
Not sure if it's a real issue or if I'm doing it wrong. When I try to compile with `mvn clean package`, I get compilation error due to javadoc (missing params for some methods).

But editing `pom.xml` according to this [answer](http://stackoverflow.com/a/16743137) solved it. I had to add this in `maven-javadoc-plugin` to make it compile.
```xml
<configuration>
    <additionalparam>-Xdoclint:none</additionalparam>
</configuration>
```

**Comment by EpicEricEE** [comment]
As I'm compiling with Java 7, I don't need this. I'm creating the javadoc extra in command line with Java 8 (because it looks better) and I always add ``-Dadditionalparam=-Xdoclint:none`` so it's the same. However I might consider adding this right into the pom file to make it simpler.
