### ISSUE TITLE
Option to allow minimum-prices to only affect buying, not selling.

### ISSUE THREAD

**Issue by mibby** [EpicEricEE/ShopChest#243]
Currently when you set a price floor, it affects both the buying and selling price. So if you want people to buy iron bars for $20 at the very minimum, you can't have people sell to the shop at a much lower cost such as $5.

Would it be possible to have an option to enable the min and max pricing so it only affects buying cost?

**Comment by EpicEricEE** [comment]
Sorry, I won't add that.
