### ISSUE TITLE
Leftover Holograms

### ISSUE THREAD

**Issue by QixyQix** [EpicEricEE/ShopChest#246]
**Minecraft version:** 1.12.2
**ShopChest Version:** 1.12.3

Players are experiencing severe FPS lag when near an area with a lot of shops. This is caused by armor stands/holograms being displayed at all times, causing the player to render over hundreds of armor stands at a point of time.

I have checked my configuration and have confirmed that `only-show-shops-in-sight` and `only-show-first-shop-in-sight` are set to true

Removing a shop also leaves behind the hologram for some weird reason and there is no way to delete the holograms apart from using the `minecraft:kill` command. But it does not resolve the issue as the plugin will respawn these holograms in the same locations moments later.

Could this be fixed, please?

**Comment by YouHaveTrouble** [comment]
Second part of the issue (leftover holograms) :
I had his problem when using defautl config for database. As soon as I plugged plugin to MySQL this problem disappeared.

But yeah, first part is true, only-show-shops-is-sight seems not to be working well.

**Comment by EpicEricEE** [comment]
Leftover holograms should be fixed now with the latest snapshot, however, I had to disable hologram interaction for that. If you want to try (will contain issues), see here: https://ci.codemc.org/job/EpicEricEE/job/ShopChest/lastSuccessfulBuild/
