### ISSUE TITLE
WorldGuard Dependency

### ISSUE THREAD

**Issue by JohnS19** [EpicEricEE/ShopChest#249]
The worldguard dependency is a bit outdated for 1.13.2 & WG 7.0.0, it seems to be causing an error in the console.

**Comment by sgdc3** [comment]
please post the exception pls

**Comment by JohnS19** [comment]
https://hastebin.com/urepizuhin.http

**Comment by JohnS19** [comment]
During boot-up: https://hastebin.com/urepizuhin.http

During actions (with worldguard integration): https://hastebin.com/zexawizito.sql

**Comment by sgdc3** [comment]
try using the latest dev build, backup your data first

**Comment by JohnS19** [comment]
Where exactly can I find that?

**Comment by JohnS19** [comment]
I am using build #41 already, where can I finder a newer version?

**Comment by JohnS19** [comment]
I have tried building directly from github as well, and it seems like there has not been a patch for it yet.

**Comment by EpicEricEE** [comment]
Fixed in latest snapshots (although all custom shop flags seem to always be denied at the moment)
