### ISSUE TITLE
Cannot change shop-limits

### ISSUE THREAD

**Issue by phost1111** [EpicEricEE/ShopChest#251]
Hey,
when changing shop-limits in the config file and rebooting or via /shop config the limit does not change and stays at 5.

**Comment by astroengisci** [comment]
I had this same issue, turns out that the actual `shop-limits` value does nothing on its own. What you want is to change `shop-limits.default`, like so:
```
shop-limits:
    default: 9001
    exclude-admin-shops: true
```

**Comment by EpicEricEE** [comment]
You config file is probably out of date. Shop limits are set via the permission `shopchest.limit.x`. To remove the limit, use `shopchest.limit.*`.
