### ISSUE TITLE
Closing Shops

### ISSUE THREAD

**Issue by milothedalmador** [EpicEricEE/ShopChest#252]
There was an issue with a corrupted chunk where multiple ShopChests were in that chunk and I now need to remove them (as the ERROR pops up in the console when loading the server) - how do I go about removing them as I've tried to "edit" the db file and it comes up with lots of symbols rather than the actual words etc. 

Thanks.

**Comment by EpicEricEE** [comment]
You'll need to open the file with a database editor. Just google for SQLite editor.
You could also enable `remove-shop-on-error` in the config to automatically remove a shop if no chest has been found or if there's no space above the chest.
