### ISSUE TITLE
Set max amount shop creation by permission

### ISSUE THREAD

**Issue by JohOply** [EpicEricEE/ShopChest#254]
Hi there
Thank you a lot for keeping plugin updated!

I have an idea: add a permission (or per-group feature in config) to set max amount of shops a player is allowed to create. Useful to give different rights to different people or groups. The permission bypass the config value. Config value is applied only by default.

For instance: 

> shopchest.maxlimit.(set the value)
> shopchest.maxlimit.45
> shopchest.maxlimit.500

**Comment by JohOply** [comment]
My bad, i just read entire config

**Comment by EpicEricEE** [comment]
This should already exist, try `shopchest.limit.x`. If a player has multiple of these permissions, the highest limit will count.

**Comment by JohOply** [comment]
Yeah I found it when I click on "create ticket", thank you ^^
