### ISSUE TITLE
Could not find translation for "block.minecraft.acacia_sign" in selected language file

### ISSUE THREAD

**Issue by Blueeyestar** [EpicEricEE/ShopChest#255]
How can I turn this off in the console or do I have to rewrite something? Who knows what advice ?

https://pastebin.com/MJdF3b32

**Comment by EpicEricEE** [comment]
If you haven't changed anything in the language file, delete it and let the plugin recreate it. If you have changed messages, make a backup and paste them in the recreated file.

**Comment by Blueeyestar** [comment]
Thank you :)
