### ISSUE TITLE
Plugin Not Loading on Start-Up [1.12.2]

### ISSUE THREAD

**Issue by PretendBullet50** [EpicEricEE/ShopChest#256]
I installed the plugin then rebooted the server and cant do "/shop" when I go to console and run "/plugins" to see what plugins are running its not loaded.

![image](https://user-images.githubusercontent.com/29534385/57659134-120e9300-7596-11e9-90c9-2c6ca53ef44a.png)

**Comment by EpicEricEE** [comment]
You surely must have got some kind information about that in the console. If you're still facing this issue, could you please paste the complete console log?

**Comment by EpicEricEE** [comment]
As far as I can tell, you don't have an economy plugin installed, so install one to make it work.
