### ISSUE TITLE
Adventure gamemode prevent buying and selling

### ISSUE THREAD

**Issue by JohOply** [EpicEricEE/ShopChest#258]
Hi there

I have a world where my players are in adventure gamemode. The problem is they are not able to sell or buy (not any message appear). If I change their gamemode for survival, message appear.

I use Spigot 1.13.2 b2146 and shopchest b48 / tested also with b52

Could you fix it please?

Thanks for reading

**Comment by EpicEricEE** [comment]
You can create shops and buy in adventure mode. Selling is not possible, since the interaction via left click is not send to the server.
