### ISSUE TITLE
Delete Shop

### ISSUE THREAD

**Issue by Blueeyestar** [EpicEricEE/ShopChest#260]
Is there a possibility to remove a shop even if the world no longer exists? 

I forgot to delete a shop when I deleted the old farm world, now this message always appears in the console:

[20:47:39] [Server thread/ERROR]: [ShopChest] No Chest found in world 'endworld' at location: 410; 41; 53

**Comment by EpicEricEE** [comment]
You can enable `remove-shop-on-error` to remove a shop from the database when there is a block above the chest or when there is no chest. That is checked every time the shops are (re-)loaded.

**Comment by Blueeyestar** [comment]
Where should it be in the config or do I have to enter it manually? remove-shop-on-error

**Comment by EpicEricEE** [comment]
See here: https://github.com/EpicEricEE/ShopChest/blob/master/src/main/resources/config.yml#L156

Maybe your config file is not up to date.

**Comment by Blueeyestar** [comment]
Thanks a lot :)
