### ISSUE TITLE
Admin command /shop removeall does not work

### ISSUE THREAD

**Issue by Magnum97** [EpicEricEE/ShopChest#262]
I have v 1.13-Snapshot running on PaperMC 1.12.2 Build # 1615

Expected behavior: /shop removeall <username> will remove all shopchests created by given username.

What happens: I get a message saying '0 Shops removed from username' 

How to replicate: Create one or more normal type shops, issue command /shop removeall <user>

The command /shop remove <user> works as expected.

**Comment by EpicEricEE** [comment]
Cannot reproduce 🤔
https://youtu.be/79dBjoU_aX4

**Comment by Magnum97** [comment]
Well fiddle sticks - thanks for taking a look at it. It did work last month and I have not changed online mode  but obviously something is interfering with it. Time to play detective.
