### ISSUE TITLE
Bugged Chests

### ISSUE THREAD

**Issue by Aurelle2** [EpicEricEE/ShopChest#265]
Hello, I found an issue that is a little bit annoying :

I used the command /shop remove all to remove all shops but then shops have been bugged.
Holograms are always here, and it's not possible to place any block at the place of the old chests. It seems to be an invisible armor stand !

It's annoying because after having uninstalled the plugin all this still exists. I don't know how to remove this ! Help please !

**Comment by EpicEricEE** [comment]
Should be fixed in the latest snapshots here (hologram interaction has been removed though): https://ci.codemc.org/job/EpicEricEE/job/ShopChest/

You'll have to remove the invisible armor stands now via `/minecraft:kill @e[type=armor_stand, nbt={Invisible: 1}]`
