### ISSUE TITLE
Server 1.14.2 - Error when trying create shop

### ISSUE THREAD

**Issue by Straiker123** [EpicEricEE/ShopChest#268]
Server: git-Spigot-df0eb25-da071ec (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)
Plugin version: Lastest Build (67)
Error: https://pastebin.com/BXCJdwhB

**Comment by EpicEricEE** [comment]
What economy plugin are you using? Also, does the error occur every time you're creating a shop?

**Comment by Straiker123** [comment]
ServerControlReloaded economy, Yes, and the shop won't be created

**Comment by Straiker123** [comment]
Now I am doing a release plugin (3.0) and found that your plugin is sending bugs when creating a store

**Comment by EpicEricEE** [comment]
What does your economy plugin return for `withdrawPlayer(player, worldName, amount)`?
There is an NPE [in line 490](https://github.com/EpicEricEE/ShopChest/blob/master/src/main/java/de/epiceric/shopchest/listeners/ShopInteractListener.java#L490), indicating that the method returns null for some reason. Could you check if there is something wrong with how you hook into Vault?

**Comment by Straiker123** [comment]
I'm hooked into Vault without problems, other plugins that need economy plugin works without problem, and here is code: `	    @Override
	    public EconomyResponse withdrawPlayer(OfflinePlayer offlinePlayer, String s, double v) {
			if (v < 0.0) {
	            return new EconomyResponse(0.0, 0.0, EconomyResponse.ResponseType.FAILURE, "Cannot withdraw negative funds");
	        }
	        double oldBalance = Loader.me.getDouble("Players."+offlinePlayer.getName()+".Money");
	        Loader.me.set("Players."+offlinePlayer.getName()+".Money", oldBalance - v);
	        API.saveChatMeConfig();
	        return new EconomyResponse(v, v, EconomyResponse.ResponseType.SUCCESS, "Succefully withdrawed $"+v+" from player "+offlinePlayer.getName());
	    }`

**Comment by Straiker123** [comment]
I don't know what I did, but the problem is fixed.
