### ISSUE TITLE
Use permissions to get shop limit

### ISSUE THREAD

**Issue by MineTheCube** [EpicEricEE/ShopChest#27]
Hi,

I think there is a better way to get shop limit of a player by using permissions. It's simpler as it doesn't require any configuration for it, and better as server admin can configure a limit per world, per group or per player. Also it doesn't even require Vault to work.

Currently, you use [this code](https://github.com/EpicEricEE/ShopChest/blob/master/src/main/java/de/epiceric/shopchest/utils/ShopUtils.java#L124-L175), but take a look at [ASkyBlock one](https://github.com/tastybento/askyblock/blob/master/src/com/wasteofplastic/askyblock/commands/IslandCmd.java#L1788-L1807).

What it does it pretty simple, it gets all current active permissions of a player (that he has or he inherits from a group), and check for those which starts by `askyblock.team.maxsize.` and get the number that follows.

Too lazy to do a PR, but this should work:

``` java
public int getShopLimit(Player p) {
    int limit = plugin.getShopChestConfig().default_limit;
    // Dynamic shopchest limit with permissions
    for (PermissionAttachmentInfo perms : player.getEffectivePermissions()) {
        if (perms.getPermission().startsWith("shopchest.limit.")) {
            if (perms.getPermission().contains("shopchest.limit.*")) {
                limit = -1; // <-- Change this value
                break;
            } else {
                // Get the max value should there be more than one
                String[] spl = perms.getPermission().split("shopchest.limit.");
                if (spl.length > 1) {
                    limit = Math.max(limit, Integer.valueOf(spl[1]));
                    // Do some sanity checking
                    if (limit < 1) {
                        limit = 1;
                    }
                }
            }
        }
    }
    return limit;
}
```

**Comment by EpicEricEE** [comment]
Will change this in the next big update (probably 1.11)
