### ISSUE TITLE
Players able to get creative mode

### ISSUE THREAD

**Issue by Magnum97** [EpicEricEE/ShopChest#270]
My players have found a glitch that allows one to get creative mode. 

The important stuff:

ShopChest Version: 1.13-SNAPSHOT
Server Version       : git-Paper-1616 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

The glitch in action: https://youtu.be/aojPKfPc_LM

**Comment by EpicEricEE** [comment]
Are you using build 63 or higher? This should have been fixed already with 2e31bbc
