### ISSUE TITLE
Shop History command.

### ISSUE THREAD

**Issue by mibby** [EpicEricEE/ShopChest#272]
Would it be possible to add a way for players to check their shop history and see when things were purchased or if new purchases were made since they last logged in?

**Comment by EpicEricEE** [comment]
You should get a message on login showing the revenue made since the last logout (in snapshot builds). A complete list of every purchase would spam the whole chat, so I won't add that.

**Comment by mibby** [comment]
Even as a command for players to check the history with pagination? Similar to the ChestShopNotifier plugin which I migrated from to ShopChest.

https://www.spigotmc.org/resources/chestshopnotifier.30313/

**Comment by EpicEricEE** [comment]
No, I don't think I'm going to add this.
