### ISSUE TITLE
Could not pass event PlayerInteractEvent to ShopChest v1.10.4

### ISSUE THREAD

**Issue by FCRev** [EpicEricEE/ShopChest#28]
[Server] ERROR Could not pass event PlayerInteractEvent to ShopChest v1.10.4
06.09 22:01:28 [Server] INFO org.bukkit.event.EventException
06.09 22:01:28 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot55.jar:git-Spigot-a9631d2-67b2424]
06.09 22:01:28 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot55.jar:git-Spigot-a9631d2-67b2424]
06.09 22:01:28 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot55.jar:git-Spigot-a9631d2-67b2424]
06.09 22:01:28 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot55.jar:git-Spigot-a9631d2-67b2424]
06.09 22:01:28 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [spigot55.jar:git-Spigot-a9631d2-67b2424]
06.09 22:01:28 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerInteractManager.a(PlayerInteractManager.java:492) [spigot55.jar:git-Spigot-a9631d2-67b2424]
06.09 22:01:28 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:890) [spigot55.jar:git-Spigot-a9631d2-67b2424]
06.09 22:01:28 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(SourceFile:55) [spigot55.jar:git-Spigot-a9631d2-67b2424]
06.09 22:01:28 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(SourceFile:11) [spigot55.jar:git-Spigot-a9631d2-67b2424]
06.09 22:01:28 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot55.jar:git-Spigot-a9631d2-67b2424]
06.09 22:01:28 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_80]
06.09 22:01:28 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_80]
06.09 22:01:28 [Server] INFO at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot55.jar:git-Spigot-a9631d2-67b2424]
06.09 22:01:28 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:737) [spigot55.jar:git-Spigot-a9631d2-67b2424]
06.09 22:01:28 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot55.jar:git-Spigot-a9631d2-67b2424]
06.09 22:01:28 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:673) [spigot55.jar:git-Spigot-a9631d2-67b2424]
06.09 22:01:28 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:572) [spigot55.jar:git-Spigot-a9631d2-67b2424]
06.09 22:01:28 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]
06.09 22:01:28 [Server] INFO Caused by: java.lang.NullPointerException
06.09 22:01:28 [Server] INFO at de.epiceric.shopchest.sql.Database.getHighestID(Database.java:130) ~[?:?]
06.09 22:01:28 [Server] INFO at de.epiceric.shopchest.sql.Database.getNextFreeID(Database.java:109) ~[?:?]
06.09 22:01:28 [Server] INFO at de.epiceric.shopchest.listeners.ShopInteractListener.create(ShopInteractListener.java:276) ~[?:?]
06.09 22:01:28 [Server] INFO at de.epiceric.shopchest.listeners.ShopInteractListener.onPlayerInteractCreate(ShopInteractListener.java:90) ~[?:?]
06.09 22:01:28 [Server] INFO at sun.reflect.GeneratedMethodAccessor679.invoke(Unknown Source) ~[?:?]
06.09 22:01:28 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_80]
06.09 22:01:28 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_80]
06.09 22:01:28 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot55.jar:git-Spigot-a9631d2-67b2424]
06.09 22:01:28 [Server] INFO ... 17 more

Love the plugin, really hoping this is fixed.

**Comment by EpicEricEE** [comment]
There must have been an issue with your SQL connection. Please send me your debug log, if it's possible (enable _enable-debug-log_ in the config, restart/reload the server and try it again)

**Comment by FCRev** [comment]
Thanks for the reply! After you told me it was SQL I went to go fix it on my own. I fixed the SQL then another error got thrown at me, but I believe it was because I was using plugman to reload the plugin individually. I restarted the server, and problem was fixed! Thanks again, leaving a good review!

**Comment by EpicEricEE** [comment]
Glad that it's fixed and thank you for the review :+1:
