### ISSUE TITLE
Incompatible with XPConomy

### ISSUE THREAD

**Issue by Buzzbugs** [EpicEricEE/ShopChest#285]
![couldnotgetbalanced](https://user-images.githubusercontent.com/54085800/65004446-c141e900-d93f-11e9-8bc3-462069309c07.jpg)

Hello,

There seems to be an incompatibility between using an XP economy plugin and Shop Chest. I will share this information with the other plugin author if needed, but I was wondering if anything could be done on this end to fix the issue?

It works perfectly fine with normal shops. But it's currently not possible to create an admin shop - when trying to do so this error comes up.

This is the economy plugin; https://www.spigotmc.org/resources/xpconomy.66775/

**Comment by EpicEricEE** [comment]
I guess XP economy does not allow withdrawing a creation price of 0. It would probably work if you set the creation price for admin shop to something other than 0.
