### ISSUE TITLE
Spawn egg OZELOT error

### ISSUE THREAD

**Issue by sigmaroot** [EpicEricEE/ShopChest#29]
Log: [pastebin](http://pastebin.com/mjkBu97t)

Please check :smiley:

**Comment by EpicEricEE** [comment]
Thank you for reporting, will fix this in the next version :+1:

**Comment by sigmaroot** [comment]
Found out: Ozelot <-> Ocelot (from API: [here](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html#OCELOT))

**Comment by EpicEricEE** [comment]
Exactly, that's the issue :v:

**Comment by sigmaroot** [comment]
When will this be updated to Spigot?
