### ISSUE TITLE
Delete shops if their chest was already removed

### ISSUE THREAD

**Issue by HgeX** [EpicEricEE/ShopChest#292]
On my server it often happens, that a player deletes his plot but forgets to delete all the shops on it, so next time when the server loads, the console is spammed with messages that the shop cannot be found. In my opinion a config option would solve this problem. If I'd set it to true for example, on startup the plugin would detect shops that don't have an existing chest, and simply delete them from the database.

**Comment by EpicEricEE** [comment]
That is exactly what the config option "remove-shop-on-error" is supposed to do :wink:

**Comment by HgeX** [comment]
Oh wow, I somehow missed that. Thank you very much! :)
