### ISSUE TITLE
Hologram not showing

### ISSUE THREAD

**Issue by FdHoly** [EpicEricEE/ShopChest#295]
![image](https://user-images.githubusercontent.com/59719548/72125851-ab4bae80-339c-11ea-8cd5-721bdbdd0714.png)

The hologram is not showing but all the function work properly, also after i remove the shop, i need to relog to make the armor stand disappear

**Comment by FdHoly** [comment]
Im playing in 14.4 server

**Comment by EpicEricEE** [comment]
You need to use a developer build for 1.13, 1.14 or 1.15 servers. See here: https://ci.codemc.io/job/EpicEricEE/job/ShopChest/
