### ISSUE TITLE
Admin Chest "Vendor not have enough money"

### ISSUE THREAD

**Issue by Dlhmach** [EpicEricEE/ShopChest#3]
When my players try to buy from a chest set as an admin chest, it says that the vendor does not have enough money. I checked the config files but didn't see anything. Any help would be appreciated, thanks :)

**Comment by EpicEricEE** [comment]
I think _(and hope)_ you mean that when your players try to **sell** something to an Admin Shop, the message occurs.
Will upload a fix now.
