### ISSUE TITLE
Written books

### ISSUE THREAD

**Issue by sigmaroot** [EpicEricEE/ShopChest#30]
Hey EpicEricEE!

I've got another issue :cry:
Some players are trying to sell written books. A shop can be created, everything is fine. And you can buy it.

But: When the shop is reloaded (Chunk reload or /shop reload), it is no more possible to buy this book, stock is 0.

Maybe something within the encode / decode functions at Utils.java or withing a calling function is wrong and catching a wrong ItemStack :cry:

Note:
Because I'm a german developer too and I love your plugin, I'm inviting you to visit us at our teamspeak and maybe have a look together at it :smile: In this case, just write me an e-mail.

**Comment by EpicEricEE** [comment]
Thanks for reporting, this is a strange issue since the item stacks are the same when serialized, but the shop still won't count it as in stock. So the encode and decode function are working as expected, but maybe there's a problem with the *Utils#getAmount* method or a method I've used in it.

**Comment by sigmaroot** [comment]
Any news?

**Comment by EpicEricEE** [comment]
Good news, I just got it working 👌
