### ISSUE TITLE
Can't Remove Shop

### ISSUE THREAD

**Issue by liaowangdezhuzhu** [EpicEricEE/ShopChest#306]
I deleted shops still have the hologram name on them and I cannot place blocks where the chest with the shop was.
I try delete plugin,but It's also there

**Comment by EpicEricEE** [comment]
Kill the armor stands manually via `/minecraft:kill @e[type=armor_stand, nbt={Invisible:1}]`

**Comment by liaowangdezhuzhu** [comment]
Thanks！Solved
