### ISSUE TITLE
Installed plugin, created shop, server crashed?

### ISSUE THREAD

**Issue by alextunbridge67** [EpicEricEE/ShopChest#308]
Like title said, using the /shop create command the server crashed, tried with eyes of ender, and granite. 

Crash report: https://pastebin.com/muDsctEt

Console log: https://pastebin.com/iA1hAQJ4

**Comment by EpicEricEE** [comment]
Does this also happen with the latest build of paper?

**Comment by alextunbridge67** [comment]
Thank you, after updating paper and a bunch of other plugins its actually working.
