### ISSUE TITLE
Floating text after uninstalling the plugin

### ISSUE THREAD

**Issue by SlimeyMations** [EpicEricEE/ShopChest#316]
I uninstalled the plugin because I did not need it anymore, however after the plugin was gone there was floating text where a shop previously was. I cannot place or remove anything in this area where the text is. Is there a place I can delete stuff like this in?
Thank you
![download (1)](https://user-images.githubusercontent.com/26635493/78841694-56045500-79fe-11ea-8539-9b3eb1893079.png)

**Comment by TheMolkaPL** [comment]
You need to remove armor stands. Go to the spectator mode and you'll see them.

**Comment by EpicEricEE** [comment]
Use the command `/minecraft:kill @e[type=armor_stand, nbt={Invisible: 1}]` to remove all invisible armor stands.
