### ISSUE TITLE
PlotSquared v5

### ISSUE THREAD

**Issue by 4Cris** [EpicEricEE/ShopChest#319]
Please update to PlotSquared v5

**Comment by mrfloris** [comment]
Same here.

Trying to strip it out, because everything we disable in config.yml gets 100% ignored.
Setting worldguard integration false and plotsquared false, it still does all the stuff and errors.

But we just keep getting errors. Looking forward to the dev updating this.

**Comment by EpicEricEE** [comment]
Please try [build 89](https://ci.codemc.io/job/EpicEricEE/job/ShopChest/), I couldn't test it since I don't have the plugin.

**Comment by mrfloris** [comment]
That seems to work for me, no error on usage, and the shops show up again. And player with perms can buy/sell.

**Comment by 4Cris** [comment]
Works fine thanks a lot!
