### ISSUE TITLE
RedProtect with ShopChest issue.

### ISSUE THREAD

**Issue by GabrielAugustoTI** [EpicEricEE/ShopChest#32]
RedProtect with ShopChest causes low spikes TPS.

http://prntscr.com/d9q0ij

**Comment by EpicEricEE** [comment]
I don't know what RedProtect has to so with this, but is it possible to provide more details? With those two numbers, I can't find out what is causing the low TPS.

**Comment by GabrielAugustoTI** [comment]
https://timings.aikar.co/v2/?id=bbc4605e928f419ba087806036bb70cf

**Comment by EpicEricEE** [comment]
Thank you. Please try [this](https://goo.gl/6xrDPI) version and tell me if it's better. 👍 
_(Also, you're running your server with 800MB RAM, which is pretty little)_

**Comment by EpicEricEE** [comment]
You could also try setting _auto-reload-time_ in the config to 0

**Comment by EpicEricEE** [comment]
As there's no more feedback, I assume this issue is no longer relevant.
