### ISSUE TITLE
Error with last build of ShopChest

### ISSUE THREAD

**Issue by jere62smi** [EpicEricEE/ShopChest#321]
http://bin.mc-imperia.fr/MjgecosAIU

**Comment by Nogapra** [comment]
Same whit SQLITE ^^
https://pastebin.com/VYM6rM9s

**Comment by EpicEricEE** [comment]
Please try again with [build 90](https://ci.codemc.io/job/EpicEricEE/job/ShopChest/) and let me know if it works.

**Comment by jere62smi** [comment]
It works. Thank
