### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by Eur0x** [EpicEricEE/ShopChest#325]
In the latest version of ShopChest-1.13-SNAPSHOT on server 1.15.2 I cannot buy items in the admin shop despite the having permissions for that

![image](https://user-images.githubusercontent.com/64858671/81093731-c79ec880-8f02-11ea-87b3-bec5246f0324.png)

![image](https://user-images.githubusercontent.com/64858671/81093740-ce2d4000-8f02-11ea-8e93-bdfc21903bb1.png)

![image](https://user-images.githubusercontent.com/64858671/81093782-dd13f280-8f02-11ea-8ae4-3ef20c88eab4.png)

**Comment by EpicEricEE** [comment]
Maybe you need to allow the flags "use-shop" (and "use-admin-shop") in worldguard, plotsquared or bentobox. Also, "shopchest.create.protected" should not be allowed for all players.
