### ISSUE TITLE
[Request] Remove the $ being automatically added into the buy and sell price string.

### ISSUE THREAD

**Issue by Repo31c** [EpicEricEE/ShopChest#327]
Hi,

I am using a different symbol my server's economy but there seems to be no way to remove the $ from the %BUY-PRICE% and %SELL-PRICE% placeholders. Could they be removed so that we can add our own into the configuration?

**Comment by EpicEricEE** [comment]
AFAIK, Vault is responsible for adding the economy sign which is gotten from the economy plugin itself.
