### ISSUE TITLE
Creative switch Problem

### ISSUE THREAD

**Issue by JaHollYT** [EpicEricEE/ShopChest#330]
Hey, i need an Option to disable that players are set to the creative mode when they want to create a shop
( example: /shop create 1 1 0 ) and got no item in there hand.
Cause they can cheat items.

Hope you can publish an update very soon or is there already an option to disable it?

**Comment by EpicEricEE** [comment]
When the players get in creative mode, they are not allowed to do anything but to select an item. If you experience that players can stay in creative mode, can you tell me what exactly you do?
Also, to disable the feature, you can set `creative-item-select` in the config to `false`
