### ISSUE TITLE
buy and sell

### ISSUE THREAD

**Issue by cewallace** [EpicEricEE/ShopChest#35]
Best Program I's seen in a log time. Good work.
But - when the display shows the Buy on the left and the Sell on the right, is there a way to reverse the mouse buttons to corresponding to the display - getting complainants .
my players used chestshop and are spoiled on clicking left to Buy and Right to Sell.
Thanks Chuck - woodenaxe.net

**Comment by EpicEricEE** [comment]
You can't do that yet, but you can for now change the hologram layout in the language file.

**Comment by cewallace** [comment]
Thanks That worked just fine.
