### ISSUE TITLE
two-line-hologram-lift doesn't work

### ISSUE THREAD

**Issue by sigmaroot** [EpicEricEE/ShopChest#38]
Running version 1.11.1

Changing the setting _two-line-hologram-lift_ does not change the hologram lift ingame.
I've tried setting it ingame by /shop config and manually in the config file and restarting the server.

**Comment by EpicEricEE** [comment]
It does work for me 😕

**Comment by sigmaroot** [comment]
Yes, _two-line-prices_ is enabled.

See the full config: [Pastebin](http://pastebin.com/NTQ7LzjU)

**Comment by sigmaroot** [comment]
Ok, you're right, this works. But it only has an effect on shops with two prices. Shops with disabled sell or disabled buy price are not affected. This would be a nice enhancement to lift the hologram in all cases. You may call it _hologram-lift_ instead of _two-line-hologram-lift_.
