### ISSUE TITLE
Dropped Items

### ISSUE THREAD

**Issue by Tomcatchriss** [EpicEricEE/ShopChest#4]
Hello, we are using now Chestshop and on our new server, we think about a new shop plugin. Your plugin is great and works good, but if I create a shop, where ist no space about the chest, the item dropps. It couldn't take, but it wouldn't despawn, too.

And in a test a build a piston behind the chest and can drop the item, too.

Is there a solution, to get this fixed?

Another thing is, that we are using Towny. Are you thinking about a towny-integration?

**Comment by EpicEricEE** [comment]
Well, sorry for the late response but the issue will be fixed in the next version.

I'm not sure what I need to add for a Towny integration, but you can tell me if you're reading this :v:
