### ISSUE TITLE
No Permission to buy and sell despite having the permissions

### ISSUE THREAD

**Issue by dwgr8golfer** [EpicEricEE/ShopChest#45]
My users have the permissions shopchest.buy, shopchest.create, and shopchest.sell.

They can create shops but not buy or sell anything from them. 
When they try to buy they get the error "You don't have permission to buy something from here"

Also when I restart the server all of the shops are removed.

I am using Bukkit 1.1 with essentials economy

**Comment by EpicEricEE** [comment]
You probably have WorldGuard installed, so you have to either disable worldguard integration in the config or allow the flags _"create-shop"_, _"use-shop"_, and _"use-admin-shop"_ depending on what you want to be allowed, or you can also grant the permission _"shopchest.worldguard.bypass"_ so players can use shops regardless of the _"use-shop"_ or _"use-admin-shop"_ flag.

When all shops are removed, do you get any error messages in the console? If you're using MySQL, did you set everything up correctly?

**Comment by jkobus** [comment]
I'm was also experiencing this issue and I'm using worldguard. 
When a user with permissions try to interact with the hologram I also get a message "Hey! You can't change that here". This happens regardless if integration with wg is enabled or not. I'm not using MySQL storage.
