### ISSUE TITLE
Auto-Reloaded memory leak

### ISSUE THREAD

**Issue by gonzalociocca** [EpicEricEE/ShopChest#46]
investigating.

**Comment by EpicEricEE** [comment]
As SQL requests are currently executed on the main thread, the auto reload method has a quite bad performance. Unfortunately, I haven't yet had time to change this.
I don't know if this is the issue you meant, but it is something that needs to be changed.

**Comment by EpicEricEE** [comment]
As SQL requests are currently executed on the main thread, the auto reload method has a quite bad performance. Unfortunately, I haven't yet had time to change this.
I don't know if this is the issue you meant, but it is something that needs to be changed.

**Comment by gonzalociocca** [comment]
nope, for some reason entities from shopchest arent removing properly on my server(its modified), i have to test better on a non-modified spigot.
