### ISSUE TITLE
Bug in 1.9

### ISSUE THREAD

**Issue by Ldcr993519867** [EpicEricEE/ShopChest#5]
in Minecraft server 1.9,if you put the item in the off hand then click a sell shop ,you can unlimited sell it , plugin won't take your item.

I'm using Plugin version 1.7.3

sorry for my bad english. =-=

**Comment by EpicEricEE** [comment]
Thank you for reporting :+1:
This is fixed [here](https://github.com/EpicEricEE/ShopChest/commit/099208de6743982882c104371cae12a1a2dbbfda) (099208de) and should be working in the next version.
