### ISSUE TITLE
ASkyblock Intergration

### ISSUE THREAD

**Issue by johnsoncui02** [EpicEricEE/ShopChest#50]
This is a skyblock server who uses ASkyblock as the main source of plugin, with it's own region protection which they don't use world guard. How can players be able to create/buy/sell without having the risk of other players visiting an island that's not own by them from removing or creating new shops without the owner's permission?

**Comment by johnsoncui02** [comment]
![image](https://cloud.githubusercontent.com/assets/23487437/21469662/2fcdee34-ca14-11e6-91a5-3c2e189110f5.png)

**Comment by johnsoncui02** [comment]
basically what im trying to say is, is there a way to protect the chest but at the same time without worldguard. If not then there's no way skyblock servers are going to be able to use this.

**Comment by johnsoncui02** [comment]
Due to this, other players on my island can also create a shop on my chests without my permission.

**Comment by EpicEricEE** [comment]
Isn't there maybe a possibility in ASkyblock to prevent players, who are not the owner of the island, to open chests on the island? That should already be enough for ShopChest to not allow that player to create a shop there.

**Comment by chillerkraft** [comment]
this is also an issue with islandworld plugin, just the fact that these plugins use there own protection plugin, shopchest doesnt YET know that we can't build on other islands so it lets us make shopchests anywhere. of course we cant open them but we can make and probably remove other people shopchests.
i hope you find a workaround for this
maybe make shopchest creation check for ability to build more instead of just through worldguard

**Comment by EpicEricEE** [comment]
If you can't open a chest, you can't create a shop there, and removing another player's shop is not allowed unless you have permission so that shouldn't be the problem.
@chillerkraft, you say that you can't open a chest but you _can_ make a shop on it if I understood correctly. This should not be possible as mentioned above, so are you sure that you don't have permission to create a shop on a protected chest?
I might add a config to switch between checking for building ability and for chest opening ability.

**Comment by chillerkraft** [comment]
i think its only asking worldguard if we can open a chest. because i cant open a chest on someone elses skyblock but i can still make a shop.
i didnt give perm for protected chests. just shopchest.create.
that would be awesome as long as its compatible with skyblock protections and not just worldguard.

**Comment by EpicEricEE** [comment]
No, it should be asking every plugin. I just looked at the source of ASkyBlock to verify that it should ask that plugin too and it should.
If you're familiar with the Bukkit API, you can see in the _ShopInteractListener_ that I'm checking if the _PlayerInteractEvent_ was cancelled by another plugin. And when ASkyblock cancels the event, ShopChest should recognize that. I haven't tried it though but I will as soon as I have time...

**Comment by chillerkraft** [comment]
sorry im using IslandWorld

**Comment by EpicEricEE** [comment]
@chillerkraft 
If you disable the _"chest-access"_ flag in the config of IslandWorld, a visitor is not allowed to create a shop. I just tried it and everything worked fine.

**Comment by chillerkraft** [comment]
i already had the flags set to false for chest acess in the islandworld config. does it need to be true?
ill try it with that latest version in a couple hours when im home. ty for quick support

**Comment by chillerkraft** [comment]
`[16:52:02] [Server thread/ERROR]: Could not load 'plugins/ShopChest-1.11.1-25bb33c.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: name '${project.name}' contains invalid characters.
	at org.bukkit.plugin.PluginDescriptionFile.loadMap(PluginDescriptionFile.java:894) ~[spigot.jar:git-Spigot-7d78b81-270755d]
	at org.bukkit.plugin.PluginDescriptionFile.<init>(PluginDescriptionFile.java:232) ~[spigot.jar:git-Spigot-7d78b81-270755d]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:157) ~[spigot.jar:git-Spigot-7d78b81-270755d]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot.jar:git-Spigot-7d78b81-270755d]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:301) [spigot.jar:git-Spigot-7d78b81-270755d]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:204) [spigot.jar:git-Spigot-7d78b81-270755d]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot.jar:git-Spigot-7d78b81-270755d]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]`

**Comment by chillerkraft** [comment]
that version you sent a link too won't load up on my serber

**Comment by EpicEricEE** [comment]
Yes, I just messed up the build. Wait a moment and I'll fix that...

**Comment by chillerkraft** [comment]
wootwoot!

**Comment by EpicEricEE** [comment]
That 💩 doesn't want to be fixed 😒

**Comment by chillerkraft** [comment]
ohnooo

**Comment by EpicEricEE** [comment]
Well, just this one [here](https://drive.google.com/open?id=0BxqKmdgOnShjSERZQXJ0SVd1YjA), it is also the latest.

**Comment by chillerkraft** [comment]
i am still able to make a shop on other peoples islands. i will try setting chest-access to true as im not sure what true and false means for islandworld flags

**Comment by chillerkraft** [comment]
tried setting it to true. can still make a shop on other islands.

**Comment by chillerkraft** [comment]
i go to another persons island and do /shop create 1 1 1 and click a chest im not able to open and it still creates the shop. with chest-access flag true and false in islandworld config

**Comment by EpicEricEE** [comment]
_chest-access_ must be false, but if you can still create a shop on a chest you cannot open, you **must** either be OP or have permission _shopchest.create.protected_. I can't explain that otherwise...
Is IslandWorld the only plugin that protects chests on your server?

**Comment by chillerkraft** [comment]
yea i tried removing all plugins except essentials cleanroomgen islandworld vault shopchest and multiverse and its still letting me create shops on other islands. well then. tell me the exact steps u took to test this because i can't reproduce success at all but you said you can
