### ISSUE TITLE
Hopper protection

### ISSUE THREAD

**Issue by Mrufkojad** [EpicEricEE/ShopChest#54]
Hi!
I'm using your plugin on my skyblock server and there is one issue that some players find important. I know there is hopper protection and if it's turned off hopper can give item to the shop, but hopper can't get item out of the shop. Is there any chance that you will give us option to choose? :)

**Comment by EpicEricEE** [comment]
Maybe another plugin is blocking it, since on my local server, I can pull things out of the shop when hopper protection is off and I can put things into the shop, even when hopper protection is turned on.

**Comment by Mrufkojad** [comment]
Okey, it's not an issue anymore, after daily restart it work like it
should. Sorry for bothering and thanks for response. By the way, your
plugin is awesome, players love it's simplicity.
