### ISSUE TITLE
Async chunk load

### ISSUE THREAD

**Issue by sigmaroot** [EpicEricEE/ShopChest#56]
Please have a look at this:

http://pastebin.com/3J3cEP59

I'm running latest build (maven build of this repo). This error caused the whole server to crash. I had to restart the server.

**Comment by EpicEricEE** [comment]
I assume this is because ShopUpdateEvent is mistakenly called asynchronously. Will push a commit in a moment, so you can try again

**Comment by sigmaroot** [comment]
Running stable for 24 hourse, I guess this is fixed :)
I'm closing it now an reopening, if some new async error occurs.
