### ISSUE TITLE
[Feature] Changeable hologram colors

### ISSUE THREAD

**Issue by weaves7** [EpicEricEE/ShopChest#58]
I really like this plugin and it is nice to see you are still actively working on it. I have not seen you on the spigot discussion  page for a while so i was getting nervous. I see here that you are fixing the errors that have been reported  by the other users and I and we thank you. You may, however, want to give an update post on the spigot discussion page.
  One feature that i would like added is the ability to change the hologram color for each shop either with a command like /shop color <colorcode> (then click the shop)  or just a field in the config.yml  to change the hologram color globally. Either way would be cool but the per shop color would be awesome. 
 Thanks for all your work on this plugin and cant wait for the new update.

**Comment by EpicEricEE** [comment]
You could add color codes to hologram messages in the language file.
Per shop is not possible, and I don't think I will implement that, as that would make customized hologram messages with colors kind of useless.

**Comment by weaves7** [comment]
Awesome this works great. I didn't know i could edit the language file in this way. Thanks!
