### ISSUE TITLE
Permission Not Work

### ISSUE THREAD

**Issue by MatinDark** [EpicEricEE/ShopChest#60]
I Use Group Managers And Essentials And i Use Vault Too Nice Plugin But When I Gave Permission to player to buy or sell or create shop say you don't have permission

**Comment by EpicEricEE** [comment]
I assume you have WorldGuard installed and that the message you get is
_"You don't have permission to buy/sell something **here**"_

To fix this, you must know that there are three custom WorldGuard flags

- _create-shop_
- _use-shop_
- _use-admin-shop_

All of them are denied by default, so you need to allow them on each region you want shop use or creation to be allowed. You could also grant the permission _"shopchest.worldguard.bypass"_ to players, so they can also use shops on regions that deny shop use _(this won't allow them to create them though)._

**Comment by EpicEricEE** [comment]
Does it work now?

**Comment by MatinDark** [comment]
Yes
