### ISSUE TITLE
NBT tag compatibility

### ISSUE THREAD

**Issue by OutcastChris** [EpicEricEE/ShopChest#62]
Just to start off this is a great plugin, however....

Items that have shops set up for them do not check for a match of NBT Tags as they are getting sold or bought to and from. Is there any way in which you can make it so the NBT Tages are used to buy and sell with? For example, a custom named item going into the shop and coming out as a normal item or a normal item going and coming out a named item is a worrying prospect since we place high value on the custom named items.

**Comment by EpicEricEE** [comment]
I'm pretty sure that at least display names are working. The rest should also be working fine except some NBT tags, but that should be fixed in the next update (8e867a7). So, what exactly is not working for you and what version are you currently using?

**Comment by OutcastChris** [comment]
I am using the ShopChests for 1.11.1 and if we sell an item without special name the item gets the special name and lore once it goes into the chest rather than cancel the trade. Same works the other way around if we place an item without the special name in a chest and someone then buys it the item will gain the special name and lore.

**Comment by OutcastChris** [comment]
Thank you for updating this (well in dev builds), my friend wants to know if you have a paypal so he can donate as he believes you are a great developer.
