### ISSUE TITLE
hologram

### ISSUE THREAD

**Issue by kratein** [EpicEricEE/ShopChest#65]
I have a problem with this value 
`# Set the maximal distance (in blocks) to the shop where the player can see the hologram.
maximal-distance: `
i tried 1, 3 and nothing. That doesn't change anything and player can see the hologram at very far perharps 50 blocks (don't know exactly).

![2017-01-21_20 15 56](https://cloud.githubusercontent.com/assets/7021079/22177031/80e59958-e016-11e6-9e7d-4e63819da27d.png)
 
it's very ugly. Can you help me to set a maximal-distance ?

**Comment by EpicEricEE** [comment]
There are some issues with holograms currently, please download the latest version from [here](http://epiceric.square7.de/bukkit/plugins/) and tell me if it works better with it.

**Comment by kratein** [comment]
ok. To make the update i just need to copy the new .jar in plugin/ and reload the ShopChest ?

**Comment by EpicEricEE** [comment]
You need replace the old ShopChest jar and reload or restart the server

**Comment by kratein** [comment]
ok. thanks, all work with the new jar.
