### ISSUE TITLE
PEX and other plugins

### ISSUE THREAD

**Issue by Endergirl2900** [EpicEricEE/ShopChest#66]
[2017-01-22-4.log.zip](https://github.com/EpicEricEE/ShopChest/files/722226/2017-01-22-4.log.zip)

Hey :)
I installed your cool looking plugin but as soon it was installed it disabled Pex, on time and other 1 or 2 plugins... :( 
I sent you the logs... maybe you can see a problem??

looking forward to hear from you soon :)

**Comment by EpicEricEE** [comment]
It seems like you got some errors in the ShopChest configuration and in the permissions file. If you want, you can send me those files and I'll check them.
