### ISSUE TITLE
Clicking actions sometimes not works.

### ISSUE THREAD

**Issue by Poweringg** [EpicEricEE/ShopChest#67]
Hi, when player creates shop, sometimes he can't remove it, and admin can't remove it too. Admin can only selling / buying items on right or left click, when is entered command "/shop remove". Player (the owner of the shop) getting no action when is right/left clicked. 

Same for "/shop info" and "/shop create"

Sometimes it works well, sometimes not, where is error?

**Comment by EpicEricEE** [comment]
Please enable debug log in the config, reload or restart the server, wait until the error appears again and send me the content of the _debug.txt_ file found in this plugin's folder.
