### ISSUE TITLE
Question - Shop Holograms

### ISSUE THREAD

**Issue by Poweringg** [EpicEricEE/ShopChest#68]
Hi, how can i hide Shop holograms by default and show it, when player looks at it? Because it's so laggy when i have ca. 100 shops at one place and ALL holos are shown. I need show holo, only when player look at it, how can i do it?

**Comment by EpicEricEE** [comment]
If you mean that even holograms of shops, that are further away than the maximal distance specified in the config, are showing, please download a version of ShopChest from [here](http://epiceric.square7.de/bukkit/plugins/).

**Comment by Poweringg** [comment]
No, i thought, when player joins the server, he sees holograms of all shops, how to hide it by default? and show hologram at certain shop when player looks at it ?

![image](https://cloud.githubusercontent.com/assets/15527318/22403685/54ce1098-e61f-11e6-9d38-4c5b4b8ef227.png)
(holograms when i joined, Holos causes some lags.)

**Comment by EpicEricEE** [comment]
Yes that's an issue with the current version. Download a version from the link above and it should work.

**Comment by Poweringg** [comment]
Yes it works at this version, i'm sorry, thanks!
