### ISSUE TITLE
Recieving wrong egg from shop

### ISSUE THREAD

**Issue by Geffel** [EpicEricEE/ShopChest#71]
Hello!

I have a problem using spawneggs. 
If you have a cow egg in your inventory and buy a chicken egg, you recieve a cow egg. The same happends when you try to sell eggs, you can sell Cow egg in chicken egg shop.

Something I can do to fix this or is it a bug? 

Thankful for help!

**Comment by EpicEricEE** [comment]
Please download a version from [here ](http://epiceric.square7.de/bukkit/plugins/)and tell me if it works.
