### ISSUE TITLE
ShopChest Lagging

### ISSUE THREAD

**Issue by Lokarda2** [EpicEricEE/ShopChest#73]
https://timings.spigotmc.org/?url=xifoqeriwi

Hi man, this is my timings, plugin is taking up a lot of CPU and RAM, any idea why ? Thanks

**Comment by EpicEricEE** [comment]
I know that it's currently quite resource heavy, but I'm not sure how to improve that.

**Comment by Viesturs88** [comment]
Yeah same here: https://paste.md-5.net/vadayamamo.pl

i run on spigot 1.11.2 sometimes cpu gets high 100% without players on server.

**Comment by EpicEricEE** [comment]
@Viesturs88 You can disable automatic shop reloads by setting _auto-reload-time_ in the config to _0_.

**Comment by Viesturs88** [comment]
@EpicEricEE Oky i will try it and i just installed DEV latest release ShopChest-1.11.1-e29da12, it seems lower cpu usage than before.

**Comment by Viesturs88** [comment]
@EpicEricEE Nope even with auto shop reload off it has same cpu usage :/ 101% oly when player is on,when i leave server cpu usage drops. :( i will check timings.

**Comment by kernelpanic3** [comment]
Just wanted to chime in to say that I've got the same issue. Oddly enough it doesn't register on timings though...

I can supply whatever you might need to fix it - this is an awesome plugin otherwise, and I intend to keep using it in spite of the bug.

**Comment by Viesturs88** [comment]
**I tested with latest dev,same cpu usage :/**

**Comment by EpicEricEE** [comment]
Can you supply new timings?
