### ISSUE TITLE
/shop create internal error

### ISSUE THREAD

**Issue by BeksOmega** [EpicEricEE/ShopChest#74]
Hello! On a server I admin it was recently discovered that doing /shop create threw an internal error. This happens with any item that I have tried. We are using the latest version and we are using the spigot unlike what happened with a similar error here: [http://www.minecraftforum.net/forums/support/server-support/2727213-i-need-some-help-d](url). 

Here is the error that comes up in console: [http://pastebin.com/dnpa2pJV](url)

Here is the debug.txt file: [http://pastebin.com/3GndDgkv](url)

Any help is much appreciated! The players on the server really love the plugin!

**Comment by EpicEricEE** [comment]
I think you misconfigured the minimum prices section. Please compare the item names in that section with the item names in the _item_names.txt_ file or download a version from [here](http://epiceric.square7.de/bukkit/plugins/) as it will show you what exactly is named wrong.

**Comment by BeksOmega** [comment]
Ok the minimum prices section is fixed and that fixed the internal error ty!

And yes we do have an elytra admin shop that is displaying the elytra item but not the pricing.
