### ISSUE TITLE
Remove as many chests you want

### ISSUE THREAD

**Issue by lcdss** [EpicEricEE/ShopChest#8]
Every time we want remove a shop, we have to send the "/shop remove" command and click in a shop. Would be better if after we type "/shop remove" could enter in a "remove mode" and this way we could remove any shop with one click until the mode was disabled.

**Comment by lcdss** [comment]
Why not permit the player destroy your own chest (chest shop) without use a command, like we did with signs (the ChestShop plugin - deprecated)?

**Comment by EpicEricEE** [comment]
That's a good idea, but you would only be able to do so on normal shops, not in admin shops, as players can buy from their own shops.
