### ISSUE TITLE
Error with Shulker box

### ISSUE THREAD

**Issue by misuda12** [EpicEricEE/ShopChest#80]
Hello,
I  noticed some errors inside my console, something with ShulkerBox, is it possible to fix somehow ?
Plugins:
PlayerHeads, dynmap, KeepItems, MinePacks, ClearLag, CrackShot, AutoMessage, Chairs, WorldBorder, AntiWorldFly, Quicksand, ProtocolLib, SimpleReserve, MultiWorld, AAC, SkinsRestorer, FastAsyncWorldEdit, iConomy, PermissionsEx, mcMMO, Stats, Vault, KeepDeathDrop, FakaHedaMinequery, WorldEdit, Essentials, LogBlock, CustomMessagesPlus, SurvivalGames, MobArena, Jobs, PerWorldInventory, HolographicDisplays, LWC, WorldGuard, MoneyDrop, Residence, EssentialsProtect, EssentialsChat, ShopChest, MineResetLite, EssentialsSpawn, CratesPlus, WorldGuardExtraFlags, AuthMe, LiteBans, CSGO-CratesPlus

**Comment by EpicEricEE** [comment]
Wait for the next update or get a developer version from [here](http://epiceric.square7.de/bukkit/plugins/).
