### ISSUE TITLE
Glitching Enchanted Items

### ISSUE THREAD

**Issue by Sidney-smi** [EpicEricEE/ShopChest#81]
Hello, a few days ago my players reported losing certain items when they created a shop. After a bit of testing, we have discovered that if you try to make a shop with an enchanted item, it gets rid of the item while making it. Ex: It took a pair of mending boots but worked just fine with normal boots. We have tested serveral times.

**Comment by EpicEricEE** [comment]
Please test if the latest developer version _(with branch 'master'),_ that you can download [here](http://epiceric.square7.de/bukkit/plugins/), has this fixed, as I think that I've found the error.
