### ISSUE TITLE
I don't arrive to install ShopChest

### ISSUE THREAD

**Issue by nathan2907** [EpicEricEE/ShopChest#82]
I put ShopChest in plugins with Vault and i have this error:  [Server thread/ERROR]: [ShopChest] Could not find any Vault economy dependency! How i can solve this probleme ? If someone can do a tutorial or manipulation at do to help me.
Thanks for all help !

**Comment by EpicEricEE** [comment]
You need to install an economy plugin.

Am 01.03.2017 05:51 schrieb "nathan2907" <notifications@github.com>:
