### ISSUE TITLE
Shortcut to buy per stack

### ISSUE THREAD

**Issue by LemonLight** [EpicEricEE/ShopChest#85]
Hi everyone, 

Is it possible, with a shop admin, to sell/buy by one item but with sneak for example to sell/buy a stack ?

For example, I created an admin shop that buy to player an Oak Wood for 1$ and sell it to 10$. Now imagine a player 64 items of Oak wood. Can he sell it in one time or does he have to click 64 time on the shop ?

Thanks in advance

**Comment by LemonLight** [comment]
Thank you for your commit, it works a half xD
Sneak + right click works
Sneak + lef click does not

**Comment by EpicEricEE** [comment]
I know, but since sneak and break removes a shop, I will need to remove that feature.
It's the same as when you try breaking a shop without sneaking, you will also sell to the shop once instead of just removing it.

**Comment by LemonLight** [comment]
Is it necessary to have sneak + break to remove a shop ? The command /shop remove is good enough

**Comment by EpicEricEE** [comment]
I think I'll keep that feature but only if you got an axe in your hand, so your can not sell a stack of something with an axe in your hand but can break a shop with it (while sneaking). You will still be able to sell items with an axe in your hand as long as you're not sneaking.

**Comment by LemonLight** [comment]
Not a bad idea :)
