### ISSUE TITLE
Maven Compilation Error

### ISSUE THREAD

**Issue by smartin1018** [EpicEricEE/ShopChest#88]
![image](https://cloud.githubusercontent.com/assets/10586186/24331491/12d126aa-11fb-11e7-8f27-75cd9449043d.png)
Have no clue what is happening here.

**Comment by EpicEricEE** [comment]
Try adding the parameter ``-U`` to your maven command to force an update of the dependencies.
For example use ``mvn clean install -U`` or ``mvn clean package -U``.

If that doesn't work, please try other suggestions from [here](http://stackoverflow.com/questions/4701532/force-maven-update).

**Comment by smartin1018** [comment]
Didn't solve the issue, same problem.

**Comment by EpicEricEE** [comment]
Then try deleting your ``.m2`` local repository folder

**Comment by smartin1018** [comment]
I did. Problem persists. I've even checked the repo and I can't find wodedit located there, would it make more sense to switch the repo worldedit is located?

**Comment by EpicEricEE** [comment]
Oh, I thought I had already added the ``sk89q-repo``. Apparently I either removed it accidentally or I had never added it. You can try adding it and if it works, I'll push a commit here too.
```xml
<repository>
    <id>sk89q-repo</id>
    <url>http://maven.sk89q.com/artifactory/repo/</url>
</repository>
```

**Comment by smartin1018** [comment]
Solved.
