### ISSUE TITLE
changing config values 

### ISSUE THREAD

**Issue by AmaranthineEon** [EpicEricEE/ShopChest#92]
Using the command /shop config <set l add l remove> <property> <value>, how can I change the shop creation price of normal to 0.

I've tried /shop config set shop-creation-price-normal 0 and multiple other variations but I can't figure it out.

**Comment by EpicEricEE** [comment]
It's _shop-creation-price.normal_. The section where the properties are located are always separated from the property by a dot. Here, the section is _shop-creation-price_ and the property is _normal_.
