### ISSUE TITLE
Towny Options

### ISSUE THREAD

**Issue by CakeLady** [EpicEricEE/ShopChest#95]
This is not a bug, but a feature request. Please forgive me if this has a solution that i have not yet found. In Towny, currently you have to have a plot set to Shop in order to create a shop, which is fine; however you cannot have a plot set as an embassy and a shop plot at the same time, which keeps anyone from building a mall area and selling "shops" to players outside their towns. Could you please make a way for players to place shops on embassy plots while still maintaining the towny protections?

**Comment by colorfulchew** [comment]
I know this isn't quite the answer you're looking for, but it should be possible to have a player from another town claim an embassy and then set the plot to a shop.

**Comment by EpicEricEE** [comment]
I'll try creating a configurable list of plot types that should allow shop creation.

**Comment by CakeLady** [comment]
I will play around with colorfulchew's suggestion, but a list of plot types would be fantastic!

**Comment by CakeLady** [comment]
That does work! Thanks! I do think having different plot types as options might be helpful though.
