### ISSUE TITLE
Very Big Timings !

### ISSUE THREAD

**Issue by TheIntelloBox** [EpicEricEE/ShopChest#96]
0.06%	   0.40%	  0.38 s	     0.20 ms	 0.2	       1.9k	    Task: ShopUpdater$1(Single)
       0.06%	   0.39%	  0.37 s	     0.19 ms	 0.2	       1.9k	    ShopUpdateListener::onShopUpdate(ShopUpdateEvent)
       0.05%	 305.78%	  0.31 s	   152.89 ms	 0.0	       0.0k	    Task: Callback$1(Single)
       0.00%	   0.00%	  0.03 s	     0.00 ms	 3.0	      37.4k	    ChestProtectListener::onItemMove(InventoryMoveItemEvent)
       0.00%	  49.38%	  0.02 s	    24.69 ms	 0.0	       0.0k	    Task: ShopChest$6(interval 24000)
       0.00%	   3.52%	  0.00 s	     1.76 ms	 0.0	       0.0k	    ShopItemListener::onPlayerLeave(PlayerQuitEvent)
       0.00%	   0.00%	  0.00 s	     0.00 ms	 0.1	       1.0k	    WorldGuardListener::onUseBlock(UseBlockEvent)
       0.00%	   0.01%	  0.00 s	     0.00 ms	 0.0	       0.4k	    ChestProtectListener::onBlockPlace(BlockPlaceEvent)
       0.00%	   0.00%	  0.00 s	     0.00 ms	 0.1	       1.1k	    ShopInteractListener::onPlayerInteract(PlayerInteractEvent)
       0.00%	   0.00%	  0.00 s	     0.00 ms	 0.0	       0.4k	    ShopItemListener::onBlockPlace(BlockPlaceEvent)
       0.00%	   0.00%	  0.00 s	     0.00 ms	 0.1	       1.1k	    ShopInteractListener::onPlayerInteractCreate(PlayerInteractEvent)
       0.00%	   0.00%	  0.00 s	     0.00 ms	 0.0	       0.4k	    ChestProtectListener::onBlockBreak(BlockBreakEvent)
       0.00%	   0.02%	  0.00 s	     0.01 ms	 0.0	       0.0k	    ShopItemListener::onBlockGrow(BlockGrowEvent)
       0.00%	   0.01%	  0.00 s	     0.01 ms	 0.0	       0.0k	    ShopInteractListener::onPlayerInteractAtEntity(PlayerInteractAtEntityEvent)
       0.00%	   0.01%	  0.00 s	     0.01 ms	 0.0	       0.0k	    ShopItemListener::onBlockSpread(BlockSpreadEvent)
       0.00%	   0.00%	  0.00 s	     0.00 ms	 0.0	       0.0k	    WorldGuardListener::onUseEntity(UseEntityEvent)
       0.00%	   0.00%	  0.00 s	     0.00 ms	 0.0	       0.0k	    WorldGuardListener::onDamageEntity(DamageEntityEvent)
       0.00%	   0.00%	  0.00 s	     0.00 ms	 0.0	       0.0k	    ShopInteractListener::onPlayerDamageEntity(EntityDamageByEntityEvent)

**Comment by EpicEricEE** [comment]
These high values are caused by the automatic shop reloading. Since the shop creation cannot be performed asynchronously, it is blocking the main thread to perform other actions which leads to lower TPS or higher timings. However, as I don't think that this feature is needed, it is removed with commit f95122d and will no longer exist in future version (and the latest [development builds](http://epiceric.square7.de/bukkit/plugins/)).
